version: "4"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: cashflow
      MONGO_INITDB_ROOT_PASSWORD: Passw0rd
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cashflow
      POSTGRES_PASSWORD: Passw0rd
      POSTGRES_DB: cashflowdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: Passw0rd
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  keycloak:
    image: keycloak/keycloak
    container_name: keycloak
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Passw0rd
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: cashflow
      KC_DB_PASSWORD: Passw0rd
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import
    command: start-dev

volumes:
  mongo_data:
  postgres_data:
  rabbitmq_data:
  keycloak_data:
